import serviceImage from '@/assets/images/service-img.webp';

import { JobItemProps } from '@/components/JobList/JobItem/JobItem.type';

export const dummy: JobItemProps[] = [
    {
        jobId: 1,
        address: 'S205 Vinhome Grand Park, Phường Long Thạnh Mỹ, TP Thủ Đức, TP HCM',
        serviceChildrenName: 'Dọn dẹp nhà cửa',
        serviceImage: serviceImage,
        serviceName: 'Mama at home',
        time: '8:00 - 10:00 thứ 2 hàng tuần',
        createAt: '2023-10-16T20:47:42',
    },
    {
        jobId: 2,
        address: 'S205 Vinhome Grand Park, Phường Long Thạnh Mỹ, TP Thủ Đức, TP HCM',
        serviceChildrenName: 'Dọn dẹp nhà cửa',
        serviceImage: serviceImage,
        serviceName: 'Mama at home',
        time: '8:00 - 10:00 thứ 2 hàng tuần',
        createAt: '2023-10-16T20:47:42',
    },
    {
        jobId: 3,
        address: 'S205 Vinhome Grand Park, Phường Long Thạnh Mỹ, TP Thủ Đức, TP HCM',
        serviceChildrenName: 'Dọn dẹp nhà cửa',
        serviceImage: serviceImage,
        serviceName: 'Mama at home',
        time: '8:00 - 10:00 thứ 2 hàng tuần',
        createAt: '2023-10-16T20:47:42',
    },
    {
        jobId: 4,
        address: 'S205 Vinhome Grand Park, Phường Long Thạnh Mỹ, TP Thủ Đức, TP HCM',
        serviceChildrenName: 'Dọn dẹp nhà cửa',
        serviceImage: serviceImage,
        serviceName: 'Mama at home',
        time: '8:00 - 10:00 thứ 2 hàng tuần',
        createAt: '2023-10-16T20:47:42',
    },
    {
        jobId: 5,
        address: 'S205 Vinhome Grand Park, Phường Long Thạnh Mỹ, TP Thủ Đức, TP HCM',
        serviceChildrenName: 'Dọn dẹp nhà cửa',
        serviceImage: serviceImage,
        serviceName: 'Mama at home',
        time: '8:00 - 10:00 thứ 2 hàng tuần',
        createAt: '2023-10-16T20:47:42',
    },
    {
        jobId: 6,
        address: 'S205 Vinhome Grand Park, Phường Long Thạnh Mỹ, TP Thủ Đức, TP HCM',
        serviceChildrenName: 'Dọn dẹp nhà cửa',
        serviceImage: serviceImage,
        serviceName: 'Mama at home',
        time: '8:00 - 10:00 thứ 2 hàng tuần',
        createAt: '2023-10-16T20:47:42',
    },
    {
        jobId: 7,
        address: 'S205 Vinhome Grand Park, Phường Long Thạnh Mỹ, TP Thủ Đức, TP HCM',
        serviceChildrenName: 'Dọn dẹp nhà cửa',
        serviceImage: serviceImage,
        serviceName: 'Mama at home',
        time: '8:00 - 10:00 thứ 2 hàng tuần',
        createAt: '2023-10-16T20:47:42',
    },
    {
        jobId: 8,
        address: 'S205 Vinhome Grand Park, Phường Long Thạnh Mỹ, TP Thủ Đức, TP HCM',
        serviceChildrenName: 'Dọn dẹp nhà cửa',
        serviceImage: serviceImage,
        serviceName: 'Mama at home',
        time: '8:00 - 10:00 thứ 2 hàng tuần',
        createAt: '2023-10-16T20:47:42',
    },
    {
        jobId: 9,
        address: 'S205 Vinhome Grand Park, Phường Long Thạnh Mỹ, TP Thủ Đức, TP HCM',
        serviceChildrenName: 'Dọn dẹp nhà cửa',
        serviceImage: serviceImage,
        serviceName: 'Mama at home',
        time: '8:00 - 10:00 thứ 2 hàng tuần',
        createAt: '2023-10-16T20:47:42',
    },
    {
        jobId: 10,
        address: 'S205 Vinhome Grand Park, Phường Long Thạnh Mỹ, TP Thủ Đức, TP HCM',
        serviceChildrenName: 'Dọn dẹp nhà cửa',
        serviceImage: serviceImage,
        serviceName: 'Mama at home',
        time: '8:00 - 10:00 thứ 2 hàng tuần',
        createAt: '2023-10-16T20:47:42',
    },
];
