import { ServiceDetailType } from '@/pages/ServiceDetail/ServiceDetail.type';
import { GroupType, SaleStatus, UnitOfMeasure } from '@/utils/enums';

export const dummy: ServiceDetailType[] = [
    {
        service: {
            serviceId: 1,
            titleName: 'Dịch vụ dọn nhà cao cấp - Dọn 1 lần là bóng loáng (Dịch vụ premium)',
            originalPrice: 8000,
            finalPrice: 5777,
            unitOfMeasure: UnitOfMeasure.KG,
            description: 'cơmmmm',
            saleStatus: SaleStatus.ONSALE,
            groupType: GroupType.HOURLY_SERVICE,
            avgRating: 3.75,
            numberOfSold: 1177825,
            mainImg: 'bit.ly/3tsNi4d',
            numberOfReview: 3,
            numberOfComment: 13,
            package: false,
        },
        typeList: [
            {
                serviceTypeId: 137,
                serviceId: 1,
                typeName: 'cơm loại 1',
            },
            {
                serviceTypeId: 138,
                serviceId: 1,
                typeName: 'cơm loại 2',
            },
        ],
        priceList: [
            {
                periodId: 53,
                serviceId: 1,
                periodValue: 1,
                periodName: 'MONTH',
                originalPrice: 103200,
                finalPrice: 51000,
            },
            {
                periodId: 54,
                serviceId: 1,
                periodValue: 3,
                periodName: 'MONTH',
                originalPrice: 24000,
                finalPrice: 1000,
            },
            {
                periodId: 55,
                serviceId: 1,
                periodValue: 6,
                periodName: 'MONTH',
                originalPrice: 48000,
                finalPrice: 5000,
            },
            {
                periodId: 56,
                serviceId: 1,
                periodValue: 9,
                periodName: 'MONTH',
                originalPrice: 72000,
                finalPrice: 8000,
            },
            {
                periodId: 57,
                serviceId: 1,
                periodValue: 12,
                periodName: 'MONTH',
                originalPrice: 96000,
                finalPrice: 12000,
            },
        ],
        images: [
            'https://www.mollymaid.com/us/en-us/molly-maid/_assets/images/services/mly-service-kitchen-2.webp',
            'https://i.ebayimg.com/images/g/DBkAAOSwA5limhuC/s-l1600.jpg',
            'https://images6.fanpop.com/image/photos/37000000/Doing-Housework-disney-37043579-1680-1050.jpg',
            'https://i.ytimg.com/vi/gmZstKaBtj8/maxresdefault.jpg',
            'https://images.squarespace-cdn.com/content/v1/5d815167fadd7b051fbda1e8/1587078895641-E42HDAP26ZJL6BO1HEA2/IMG_0801e.jpg',
            'https://www.happywater.my/wp-content/uploads/2020/07/Water-Delivery-malaysia.jpg',
            'https://res.cloudinary.com/jerrick/image/upload/c_scale,f_jpg,q_auto/5e88760f9671a2001cc57c50.jpg',
        ],
    },
    {
        service: {
            serviceId: 2,
            titleName: 'Dịch vụ dọn nhà cao cấp - Dọn 1 lần là bóng loáng (Dịch vụ premium)',
            originalPrice: 8000,
            finalPrice: 5777,
            unitOfMeasure: UnitOfMeasure.KG,
            description: 'cơmmmm',
            saleStatus: SaleStatus.DISCONTINUED,
            groupType: GroupType.HOURLY_SERVICE,
            avgRating: 3.75,
            numberOfSold: 1177825,
            mainImg: 'bit.ly/3tsNi4d',
            numberOfReview: 3,
            numberOfComment: 13,
            package: false,
        },
        typeList: [
            {
                serviceTypeId: 137,
                serviceId: 1,
                typeName: 'cơm loại 1',
            },
            {
                serviceTypeId: 138,
                serviceId: 1,
                typeName: 'cơm loại 2',
            },
        ],
        priceList: [
            {
                periodId: 53,
                serviceId: 1,
                periodValue: 1,
                periodName: 'MONTH',
                originalPrice: 103200,
                finalPrice: 51000,
            },
            {
                periodId: 54,
                serviceId: 1,
                periodValue: 3,
                periodName: 'MONTH',
                originalPrice: 24000,
                finalPrice: 1000,
            },
            {
                periodId: 55,
                serviceId: 1,
                periodValue: 6,
                periodName: 'MONTH',
                originalPrice: 48000,
                finalPrice: 5000,
            },
            {
                periodId: 56,
                serviceId: 1,
                periodValue: 9,
                periodName: 'MONTH',
                originalPrice: 72000,
                finalPrice: 8000,
            },
            {
                periodId: 57,
                serviceId: 1,
                periodValue: 12,
                periodName: 'MONTH',
                originalPrice: 96000,
                finalPrice: 12000,
            },
        ],
        images: [
            'https://www.mollymaid.com/us/en-us/molly-maid/_assets/images/services/mly-service-kitchen-2.webp',
            'https://i.ebayimg.com/images/g/DBkAAOSwA5limhuC/s-l1600.jpg',
            'https://images6.fanpop.com/image/photos/37000000/Doing-Housework-disney-37043579-1680-1050.jpg',
            'https://i.ytimg.com/vi/gmZstKaBtj8/maxresdefault.jpg',
            'https://images.squarespace-cdn.com/content/v1/5d815167fadd7b051fbda1e8/1587078895641-E42HDAP26ZJL6BO1HEA2/IMG_0801e.jpg',
            'https://www.happywater.my/wp-content/uploads/2020/07/Water-Delivery-malaysia.jpg',
            'https://res.cloudinary.com/jerrick/image/upload/c_scale,f_jpg,q_auto/5e88760f9671a2001cc57c50.jpg',
        ],
    },
    {
        service: {
            serviceId: 3,
            titleName: 'Dịch vụ dọn nhà cao cấp - Dọn 1 lần là bóng loáng (Dịch vụ premium)',
            originalPrice: 8000,
            finalPrice: 5777,
            unitOfMeasure: UnitOfMeasure.KG,
            description: 'cơmmmm',
            saleStatus: SaleStatus.DISCONTINUED,
            groupType: GroupType.HOURLY_SERVICE,
            avgRating: 3.75,
            numberOfSold: 1177825,
            mainImg: 'bit.ly/3tsNi4d',
            numberOfReview: 3,
            numberOfComment: 13,
            package: false,
        },
        typeList: [
            {
                serviceTypeId: 137,
                serviceId: 1,
                typeName: 'cơm loại 1',
            },
            {
                serviceTypeId: 138,
                serviceId: 1,
                typeName: 'cơm loại 2',
            },
        ],
        priceList: [
            {
                periodId: 53,
                serviceId: 1,
                periodValue: 1,
                periodName: 'MONTH',
                originalPrice: 103200,
                finalPrice: 51000,
            },
            {
                periodId: 54,
                serviceId: 1,
                periodValue: 3,
                periodName: 'MONTH',
                originalPrice: 24000,
                finalPrice: 1000,
            },
            {
                periodId: 55,
                serviceId: 1,
                periodValue: 6,
                periodName: 'MONTH',
                originalPrice: 48000,
                finalPrice: 5000,
            },
            {
                periodId: 56,
                serviceId: 1,
                periodValue: 9,
                periodName: 'MONTH',
                originalPrice: 72000,
                finalPrice: 8000,
            },
            {
                periodId: 57,
                serviceId: 1,
                periodValue: 12,
                periodName: 'MONTH',
                originalPrice: 96000,
                finalPrice: 12000,
            },
        ],
        images: [
            'https://www.mollymaid.com/us/en-us/molly-maid/_assets/images/services/mly-service-kitchen-2.webp',
            'https://i.ebayimg.com/images/g/DBkAAOSwA5limhuC/s-l1600.jpg',
            'https://images6.fanpop.com/image/photos/37000000/Doing-Housework-disney-37043579-1680-1050.jpg',
            'https://i.ytimg.com/vi/gmZstKaBtj8/maxresdefault.jpg',
            'https://images.squarespace-cdn.com/content/v1/5d815167fadd7b051fbda1e8/1587078895641-E42HDAP26ZJL6BO1HEA2/IMG_0801e.jpg',
            'https://www.happywater.my/wp-content/uploads/2020/07/Water-Delivery-malaysia.jpg',
            'https://res.cloudinary.com/jerrick/image/upload/c_scale,f_jpg,q_auto/5e88760f9671a2001cc57c50.jpg',
        ],
    },
    {
        service: {
            serviceId: 4,
            titleName: 'Dịch vụ dọn nhà cao cấp - Dọn 1 lần là bóng loáng (Dịch vụ premium)',
            originalPrice: 8000,
            finalPrice: 5777,
            unitOfMeasure: UnitOfMeasure.KG,
            description: 'cơmmmm',
            saleStatus: SaleStatus.ONSALE,
            groupType: GroupType.HOURLY_SERVICE,
            avgRating: 3.75,
            numberOfSold: 1177825,
            mainImg: 'bit.ly/3tsNi4d',
            numberOfReview: 3,
            numberOfComment: 13,
            package: false,
        },
        typeList: [
            {
                serviceTypeId: 137,
                serviceId: 1,
                typeName: 'cơm loại 1',
            },
            {
                serviceTypeId: 138,
                serviceId: 1,
                typeName: 'cơm loại 2',
            },
        ],
        priceList: [
            {
                periodId: 53,
                serviceId: 1,
                periodValue: 1,
                periodName: 'MONTH',
                originalPrice: 103200,
                finalPrice: 51000,
            },
            {
                periodId: 54,
                serviceId: 1,
                periodValue: 3,
                periodName: 'MONTH',
                originalPrice: 24000,
                finalPrice: 1000,
            },
            {
                periodId: 55,
                serviceId: 1,
                periodValue: 6,
                periodName: 'MONTH',
                originalPrice: 48000,
                finalPrice: 5000,
            },
            {
                periodId: 56,
                serviceId: 1,
                periodValue: 9,
                periodName: 'MONTH',
                originalPrice: 72000,
                finalPrice: 8000,
            },
            {
                periodId: 57,
                serviceId: 1,
                periodValue: 12,
                periodName: 'MONTH',
                originalPrice: 96000,
                finalPrice: 12000,
            },
        ],
        images: [
            'https://www.mollymaid.com/us/en-us/molly-maid/_assets/images/services/mly-service-kitchen-2.webp',
            'https://i.ebayimg.com/images/g/DBkAAOSwA5limhuC/s-l1600.jpg',
            'https://images6.fanpop.com/image/photos/37000000/Doing-Housework-disney-37043579-1680-1050.jpg',
            'https://i.ytimg.com/vi/gmZstKaBtj8/maxresdefault.jpg',
            'https://images.squarespace-cdn.com/content/v1/5d815167fadd7b051fbda1e8/1587078895641-E42HDAP26ZJL6BO1HEA2/IMG_0801e.jpg',
            'https://www.happywater.my/wp-content/uploads/2020/07/Water-Delivery-malaysia.jpg',
            'https://res.cloudinary.com/jerrick/image/upload/c_scale,f_jpg,q_auto/5e88760f9671a2001cc57c50.jpg',
        ],
    },
    {
        service: {
            serviceId: 5,
            titleName: 'Dịch vụ dọn nhà cao cấp - Dọn 1 lần là bóng loáng (Dịch vụ premium)',
            originalPrice: 8000,
            finalPrice: 5777,
            unitOfMeasure: UnitOfMeasure.KG,
            description: 'cơmmmm',
            saleStatus: SaleStatus.ONSALE,
            groupType: GroupType.HOURLY_SERVICE,
            avgRating: 3.75,
            numberOfSold: 1177825,
            mainImg: 'bit.ly/3tsNi4d',
            numberOfReview: 3,
            numberOfComment: 13,
            package: false,
        },
        typeList: [
            {
                serviceTypeId: 137,
                serviceId: 1,
                typeName: 'cơm loại 1',
            },
            {
                serviceTypeId: 138,
                serviceId: 1,
                typeName: 'cơm loại 2',
            },
        ],
        priceList: [
            {
                periodId: 53,
                serviceId: 1,
                periodValue: 1,
                periodName: 'MONTH',
                originalPrice: 103200,
                finalPrice: 51000,
            },
            {
                periodId: 54,
                serviceId: 1,
                periodValue: 3,
                periodName: 'MONTH',
                originalPrice: 24000,
                finalPrice: 1000,
            },
            {
                periodId: 55,
                serviceId: 1,
                periodValue: 6,
                periodName: 'MONTH',
                originalPrice: 48000,
                finalPrice: 5000,
            },
            {
                periodId: 56,
                serviceId: 1,
                periodValue: 9,
                periodName: 'MONTH',
                originalPrice: 72000,
                finalPrice: 8000,
            },
            {
                periodId: 57,
                serviceId: 1,
                periodValue: 12,
                periodName: 'MONTH',
                originalPrice: 96000,
                finalPrice: 12000,
            },
        ],
        images: [
            'https://www.mollymaid.com/us/en-us/molly-maid/_assets/images/services/mly-service-kitchen-2.webp',
            'https://i.ebayimg.com/images/g/DBkAAOSwA5limhuC/s-l1600.jpg',
            'https://images6.fanpop.com/image/photos/37000000/Doing-Housework-disney-37043579-1680-1050.jpg',
            'https://i.ytimg.com/vi/gmZstKaBtj8/maxresdefault.jpg',
            'https://images.squarespace-cdn.com/content/v1/5d815167fadd7b051fbda1e8/1587078895641-E42HDAP26ZJL6BO1HEA2/IMG_0801e.jpg',
            'https://www.happywater.my/wp-content/uploads/2020/07/Water-Delivery-malaysia.jpg',
            'https://res.cloudinary.com/jerrick/image/upload/c_scale,f_jpg,q_auto/5e88760f9671a2001cc57c50.jpg',
        ],
    },
    {
        service: {
            serviceId: 6,
            titleName: 'Dịch vụ dọn nhà cao cấp - Dọn 1 lần là bóng loáng (Dịch vụ premium)',
            originalPrice: 8000,
            finalPrice: 5777,
            unitOfMeasure: UnitOfMeasure.KG,
            description: 'cơmmmm',
            saleStatus: SaleStatus.ONSALE,
            groupType: GroupType.HOURLY_SERVICE,
            avgRating: 3.75,
            numberOfSold: 1177825,
            mainImg: 'bit.ly/3tsNi4d',
            numberOfReview: 3,
            numberOfComment: 13,
            package: false,
        },
        typeList: [
            {
                serviceTypeId: 137,
                serviceId: 1,
                typeName: 'cơm loại 1',
            },
            {
                serviceTypeId: 138,
                serviceId: 1,
                typeName: 'cơm loại 2',
            },
        ],
        priceList: [
            {
                periodId: 53,
                serviceId: 1,
                periodValue: 1,
                periodName: 'MONTH',
                originalPrice: 103200,
                finalPrice: 51000,
            },
            {
                periodId: 54,
                serviceId: 1,
                periodValue: 3,
                periodName: 'MONTH',
                originalPrice: 24000,
                finalPrice: 1000,
            },
            {
                periodId: 55,
                serviceId: 1,
                periodValue: 6,
                periodName: 'MONTH',
                originalPrice: 48000,
                finalPrice: 5000,
            },
            {
                periodId: 56,
                serviceId: 1,
                periodValue: 9,
                periodName: 'MONTH',
                originalPrice: 72000,
                finalPrice: 8000,
            },
            {
                periodId: 57,
                serviceId: 1,
                periodValue: 12,
                periodName: 'MONTH',
                originalPrice: 96000,
                finalPrice: 12000,
            },
        ],
        images: [
            'https://www.mollymaid.com/us/en-us/molly-maid/_assets/images/services/mly-service-kitchen-2.webp',
            'https://i.ebayimg.com/images/g/DBkAAOSwA5limhuC/s-l1600.jpg',
            'https://images6.fanpop.com/image/photos/37000000/Doing-Housework-disney-37043579-1680-1050.jpg',
            'https://i.ytimg.com/vi/gmZstKaBtj8/maxresdefault.jpg',
            'https://images.squarespace-cdn.com/content/v1/5d815167fadd7b051fbda1e8/1587078895641-E42HDAP26ZJL6BO1HEA2/IMG_0801e.jpg',
            'https://www.happywater.my/wp-content/uploads/2020/07/Water-Delivery-malaysia.jpg',
            'https://res.cloudinary.com/jerrick/image/upload/c_scale,f_jpg,q_auto/5e88760f9671a2001cc57c50.jpg',
        ],
    },
    {
        service: {
            serviceId: 7,
            titleName: 'Dịch vụ dọn nhà cao cấp - Dọn 1 lần là bóng loáng (Dịch vụ premium)',
            originalPrice: 8000,
            finalPrice: 5777,
            unitOfMeasure: UnitOfMeasure.KG,
            description: 'cơmmmm',
            saleStatus: SaleStatus.ONSALE,
            groupType: GroupType.HOURLY_SERVICE,
            avgRating: 3.75,
            numberOfSold: 1177825,
            mainImg: 'bit.ly/3tsNi4d',
            numberOfReview: 3,
            numberOfComment: 13,
            package: false,
        },
        typeList: [
            {
                serviceTypeId: 137,
                serviceId: 1,
                typeName: 'cơm loại 1',
            },
            {
                serviceTypeId: 138,
                serviceId: 1,
                typeName: 'cơm loại 2',
            },
        ],
        priceList: [
            {
                periodId: 53,
                serviceId: 1,
                periodValue: 1,
                periodName: 'MONTH',
                originalPrice: 103200,
                finalPrice: 51000,
            },
            {
                periodId: 54,
                serviceId: 1,
                periodValue: 3,
                periodName: 'MONTH',
                originalPrice: 24000,
                finalPrice: 1000,
            },
            {
                periodId: 55,
                serviceId: 1,
                periodValue: 6,
                periodName: 'MONTH',
                originalPrice: 48000,
                finalPrice: 5000,
            },
            {
                periodId: 56,
                serviceId: 1,
                periodValue: 9,
                periodName: 'MONTH',
                originalPrice: 72000,
                finalPrice: 8000,
            },
            {
                periodId: 57,
                serviceId: 1,
                periodValue: 12,
                periodName: 'MONTH',
                originalPrice: 96000,
                finalPrice: 12000,
            },
        ],
        images: [
            'https://www.mollymaid.com/us/en-us/molly-maid/_assets/images/services/mly-service-kitchen-2.webp',
            'https://i.ebayimg.com/images/g/DBkAAOSwA5limhuC/s-l1600.jpg',
            'https://images6.fanpop.com/image/photos/37000000/Doing-Housework-disney-37043579-1680-1050.jpg',
            'https://i.ytimg.com/vi/gmZstKaBtj8/maxresdefault.jpg',
            'https://images.squarespace-cdn.com/content/v1/5d815167fadd7b051fbda1e8/1587078895641-E42HDAP26ZJL6BO1HEA2/IMG_0801e.jpg',
            'https://www.happywater.my/wp-content/uploads/2020/07/Water-Delivery-malaysia.jpg',
            'https://res.cloudinary.com/jerrick/image/upload/c_scale,f_jpg,q_auto/5e88760f9671a2001cc57c50.jpg',
        ],
    },
    {
        service: {
            serviceId: 8,
            titleName: 'Dịch vụ dọn nhà cao cấp - Dọn 1 lần là bóng loáng (Dịch vụ premium)',
            originalPrice: 8000,
            finalPrice: 5777,
            unitOfMeasure: UnitOfMeasure.KG,
            description: 'cơmmmm',
            saleStatus: SaleStatus.ONSALE,
            groupType: GroupType.HOURLY_SERVICE,
            avgRating: 3.75,
            numberOfSold: 1177825,
            mainImg: 'bit.ly/3tsNi4d',
            numberOfReview: 3,
            numberOfComment: 13,
            package: false,
        },
        typeList: [
            {
                serviceTypeId: 137,
                serviceId: 1,
                typeName: 'cơm loại 1',
            },
            {
                serviceTypeId: 138,
                serviceId: 1,
                typeName: 'cơm loại 2',
            },
        ],
        priceList: [
            {
                periodId: 53,
                serviceId: 1,
                periodValue: 1,
                periodName: 'MONTH',
                originalPrice: 103200,
                finalPrice: 51000,
            },
            {
                periodId: 54,
                serviceId: 1,
                periodValue: 3,
                periodName: 'MONTH',
                originalPrice: 24000,
                finalPrice: 1000,
            },
            {
                periodId: 55,
                serviceId: 1,
                periodValue: 6,
                periodName: 'MONTH',
                originalPrice: 48000,
                finalPrice: 5000,
            },
            {
                periodId: 56,
                serviceId: 1,
                periodValue: 9,
                periodName: 'MONTH',
                originalPrice: 72000,
                finalPrice: 8000,
            },
            {
                periodId: 57,
                serviceId: 1,
                periodValue: 12,
                periodName: 'MONTH',
                originalPrice: 96000,
                finalPrice: 12000,
            },
        ],
        images: [
            'https://www.mollymaid.com/us/en-us/molly-maid/_assets/images/services/mly-service-kitchen-2.webp',
            'https://i.ebayimg.com/images/g/DBkAAOSwA5limhuC/s-l1600.jpg',
            'https://images6.fanpop.com/image/photos/37000000/Doing-Housework-disney-37043579-1680-1050.jpg',
            'https://i.ytimg.com/vi/gmZstKaBtj8/maxresdefault.jpg',
            'https://images.squarespace-cdn.com/content/v1/5d815167fadd7b051fbda1e8/1587078895641-E42HDAP26ZJL6BO1HEA2/IMG_0801e.jpg',
            'https://www.happywater.my/wp-content/uploads/2020/07/Water-Delivery-malaysia.jpg',
            'https://res.cloudinary.com/jerrick/image/upload/c_scale,f_jpg,q_auto/5e88760f9671a2001cc57c50.jpg',
        ],
    },
    {
        service: {
            serviceId: 9,
            titleName: 'Dịch vụ dọn nhà cao cấp - Dọn 1 lần là bóng loáng (Dịch vụ premium)',
            originalPrice: 8000,
            finalPrice: 5777,
            unitOfMeasure: UnitOfMeasure.KG,
            description: 'cơmmmm',
            saleStatus: SaleStatus.ONSALE,
            groupType: GroupType.HOURLY_SERVICE,
            avgRating: 3.75,
            numberOfSold: 1177825,
            mainImg: 'bit.ly/3tsNi4d',
            numberOfReview: 3,
            numberOfComment: 13,
            package: false,
        },
        typeList: [
            {
                serviceTypeId: 137,
                serviceId: 1,
                typeName: 'cơm loại 1',
            },
            {
                serviceTypeId: 138,
                serviceId: 1,
                typeName: 'cơm loại 2',
            },
        ],
        priceList: [
            {
                periodId: 53,
                serviceId: 1,
                periodValue: 1,
                periodName: 'MONTH',
                originalPrice: 103200,
                finalPrice: 51000,
            },
            {
                periodId: 54,
                serviceId: 1,
                periodValue: 3,
                periodName: 'MONTH',
                originalPrice: 24000,
                finalPrice: 1000,
            },
            {
                periodId: 55,
                serviceId: 1,
                periodValue: 6,
                periodName: 'MONTH',
                originalPrice: 48000,
                finalPrice: 5000,
            },
            {
                periodId: 56,
                serviceId: 1,
                periodValue: 9,
                periodName: 'MONTH',
                originalPrice: 72000,
                finalPrice: 8000,
            },
            {
                periodId: 57,
                serviceId: 1,
                periodValue: 12,
                periodName: 'MONTH',
                originalPrice: 96000,
                finalPrice: 12000,
            },
        ],
        images: [
            'https://www.mollymaid.com/us/en-us/molly-maid/_assets/images/services/mly-service-kitchen-2.webp',
            'https://i.ebayimg.com/images/g/DBkAAOSwA5limhuC/s-l1600.jpg',
            'https://images6.fanpop.com/image/photos/37000000/Doing-Housework-disney-37043579-1680-1050.jpg',
            'https://i.ytimg.com/vi/gmZstKaBtj8/maxresdefault.jpg',
            'https://images.squarespace-cdn.com/content/v1/5d815167fadd7b051fbda1e8/1587078895641-E42HDAP26ZJL6BO1HEA2/IMG_0801e.jpg',
            'https://www.happywater.my/wp-content/uploads/2020/07/Water-Delivery-malaysia.jpg',
            'https://res.cloudinary.com/jerrick/image/upload/c_scale,f_jpg,q_auto/5e88760f9671a2001cc57c50.jpg',
        ],
    },
    {
        service: {
            serviceId: 10,
            titleName: 'Dịch vụ dọn nhà cao cấp - Dọn 1 lần là bóng loáng (Dịch vụ premium)',
            originalPrice: 8000,
            finalPrice: 5777,
            unitOfMeasure: UnitOfMeasure.KG,
            description: 'cơmmmm',
            saleStatus: SaleStatus.ONSALE,
            groupType: GroupType.HOURLY_SERVICE,
            avgRating: 3.75,
            numberOfSold: 1177825,
            mainImg: 'bit.ly/3tsNi4d',
            numberOfReview: 3,
            numberOfComment: 13,
            package: false,
        },
        typeList: [
            {
                serviceTypeId: 137,
                serviceId: 1,
                typeName: 'cơm loại 1',
            },
            {
                serviceTypeId: 138,
                serviceId: 1,
                typeName: 'cơm loại 2',
            },
        ],
        priceList: [
            {
                periodId: 53,
                serviceId: 1,
                periodValue: 1,
                periodName: 'MONTH',
                originalPrice: 103200,
                finalPrice: 51000,
            },
            {
                periodId: 54,
                serviceId: 1,
                periodValue: 3,
                periodName: 'MONTH',
                originalPrice: 24000,
                finalPrice: 1000,
            },
            {
                periodId: 55,
                serviceId: 1,
                periodValue: 6,
                periodName: 'MONTH',
                originalPrice: 48000,
                finalPrice: 5000,
            },
            {
                periodId: 56,
                serviceId: 1,
                periodValue: 9,
                periodName: 'MONTH',
                originalPrice: 72000,
                finalPrice: 8000,
            },
            {
                periodId: 57,
                serviceId: 1,
                periodValue: 12,
                periodName: 'MONTH',
                originalPrice: 96000,
                finalPrice: 12000,
            },
        ],
        images: [
            'https://www.mollymaid.com/us/en-us/molly-maid/_assets/images/services/mly-service-kitchen-2.webp',
            'https://i.ebayimg.com/images/g/DBkAAOSwA5limhuC/s-l1600.jpg',
            'https://images6.fanpop.com/image/photos/37000000/Doing-Housework-disney-37043579-1680-1050.jpg',
            'https://i.ytimg.com/vi/gmZstKaBtj8/maxresdefault.jpg',
            'https://images.squarespace-cdn.com/content/v1/5d815167fadd7b051fbda1e8/1587078895641-E42HDAP26ZJL6BO1HEA2/IMG_0801e.jpg',
            'https://www.happywater.my/wp-content/uploads/2020/07/Water-Delivery-malaysia.jpg',
            'https://res.cloudinary.com/jerrick/image/upload/c_scale,f_jpg,q_auto/5e88760f9671a2001cc57c50.jpg',
        ],
    },
    {
        service: {
            serviceId: 11,
            titleName: 'Dịch vụ dọn nhà bình thường - Dọn 1 lần là bóng loáng (Dịch vụ premium)',
            originalPrice: 135571,
            finalPrice: 135571,
            unitOfMeasure: UnitOfMeasure.COMBO,
            description:
                'Displaced fracture of distal phalanx of left little finger, subsequent encounter for fracture with delayed healing',
            saleStatus: SaleStatus.DISCONTINUED,
            groupType: GroupType.DELIVERY_SERVICE,
            avgRating: 0,
            numberOfSold: 4,
            mainImg: 'bit.ly/3tsNi4d',
            numberOfReview: 0,
            numberOfComment: 0,
            package: true,
        },
        packageServiceItemList: [
            {
                packageServiceId: 11,
                singleServiceId: 1,
                quantity: 11,
                description: 'Cơm sườn chả : cơmmmm',
            },
            {
                packageServiceId: 11,
                singleServiceId: 2,
                quantity: 25,
                description: 'Lau nhà : 70-79% bdy brn/40-49% 3d',
            },
            {
                packageServiceId: 11,
                singleServiceId: 3,
                quantity: 14,
                description: 'Dịch vụ quét rác : DICH VU QUET RAC SO 1 VIET NAM',
            },
        ],
        priceList: [
            {
                periodId: 9,
                serviceId: 11,
                periodValue: 3,
                periodName: 'MONTH',
                originalPrice: 6000,
                finalPrice: 1000,
            },
            {
                periodId: 10,
                serviceId: 11,
                periodValue: 6,
                periodName: 'MONTH',
                originalPrice: 12000,
                finalPrice: 2000,
            },
            {
                periodId: 11,
                serviceId: 11,
                periodValue: 9,
                periodName: 'MONTH',
                originalPrice: 18000,
                finalPrice: 3000,
            },
            {
                periodId: 12,
                serviceId: 11,
                periodValue: 12,
                periodName: 'MONTH',
                originalPrice: 2024000,
                finalPrice: 900000,
            },
        ],
        images: [
            'https://www.mollymaid.com/us/en-us/molly-maid/_assets/images/services/mly-service-kitchen-2.webp',
            'https://i.ebayimg.com/images/g/DBkAAOSwA5limhuC/s-l1600.jpg',
            'https://images6.fanpop.com/image/photos/37000000/Doing-Housework-disney-37043579-1680-1050.jpg',
            'https://i.ytimg.com/vi/gmZstKaBtj8/maxresdefault.jpg',
            'https://images.squarespace-cdn.com/content/v1/5d815167fadd7b051fbda1e8/1587078895641-E42HDAP26ZJL6BO1HEA2/IMG_0801e.jpg',
            'https://www.happywater.my/wp-content/uploads/2020/07/Water-Delivery-malaysia.jpg',
            'https://res.cloudinary.com/jerrick/image/upload/c_scale,f_jpg,q_auto/5e88760f9671a2001cc57c50.jpg',
        ],
    },
];
