export const notifications = [
    {
        notificationId: 2,
        userId: 65,
        notificationCreatedAt: '2023-11-12T11:46:58.839',
        message: 'hello ba gia',
        title: 'string',
        entityId: 1,
        read: true,
    },
    {
        notificationId: 3,
        userId: 65,
        notificationCreatedAt: '2023-11-12T11:46:58.839',
        message: 'hello ba gia',
        title: 'string',
        entityId: 1,
        read: false,
    },
    {
        notificationId: 4,
        userId: 65,
        notificationCreatedAt: '2023-11-12T11:46:58.839',
        message: 'hello ba gia',
        title: 'string',
        entityId: 1,
        read: false,
    },
    {
        notificationId: 5,
        userId: 65,
        notificationCreatedAt: '2023-11-12T11:46:58.839',
        message: 'hello ba gia',
        title: 'string',
        entityId: 1,
        read: true,
    },
    {
        notificationId: 6,
        userId: 65,
        notificationCreatedAt: '2023-11-12T11:46:58.839',
        message: 'hello ba gia',
        title: 'string',
        entityId: 1,
        read: false,
    },
    {
        notificationId: 7,
        userId: 65,
        notificationCreatedAt: '2023-11-12T11:46:58.839',
        message: 'hello ba gia',
        title: 'string',
        entityId: 1,
        read: true,
    },
    {
        notificationId: 8,
        userId: 65,
        notificationCreatedAt: '2023-11-12T11:46:58.839',
        message: 'hello ba gia',
        title: 'string',
        entityId: 1,
        read: true,
    },
];
