import serviceImage from '@/assets/images/service-img.webp';
import { JobItemProps } from '@/components/JobList/JobItem/JobItem.type';
import { UserInfoType } from '@/pages/Customer/Checkout/Checkout.type';
import { Role, Status } from '@/utils/enums';

export const userDummy: UserInfoType = {
    address: 'S205 Vinhome Grand Park, Phường Long Thạnh Mỹ, TP Thủ Đức, TP HCM',
    avatar: '',
    emailAddress: '',
    emailValidationStatus: true,
    fullName: 'Duong Hoang Nam',
    phoneNumber: '0916207758',
    role: Role.CUSTOMER,
    userId: 1,
};

export const dummy: JobItemProps[] = [
    {
        jobId: 1,
        address:
            'Nhà Văn hóa Sinh viên TP.HCM, Lưu Hữu Phước, Đông Hòa, Dĩ An, Bình Dương, Việt Nam',
        serviceChildrenName: 'Dọn dẹp nhà cửa',
        serviceImage: serviceImage,
        serviceName: 'Mama at home',
        time: '8:00 - 10:00 thứ 2 hàng tuần',
        createAt: '2023-10-16T20:47:42',
        startDate: '11/9/2023',
        endDate: '11/12/2023',
        status: Status.DONE,
        package: true,
        note: 'Cần nhân viên tuổi 18+, có ngoại hình, chăm chỉ, đảm đang',
    },
    {
        jobId: 2,
        address:
            'Nhà Văn hóa Sinh viên TP.HCM, Lưu Hữu Phước, Đông Hòa, Dĩ An, Bình Dương, Việt Nam',
        serviceChildrenName: 'Dọn dẹp nhà cửa',
        serviceImage: serviceImage,
        serviceName: 'Mama at home',
        time: '8:00 - 10:00 thứ 2 hàng tuần',
        createAt: '2023-10-16T20:47:42',
        startDate: '11/9/2023',
        endDate: '11/12/2023',
        status: Status.DONE,
        package: false,
        note: 'Cần nhân viên tuổi 18+, có ngoại hình, chăm chỉ, đảm đang',
    },
    {
        jobId: 3,
        address:
            'Nhà Văn hóa Sinh viên TP.HCM, Lưu Hữu Phước, Đông Hòa, Dĩ An, Bình Dương, Việt Nam',
        serviceChildrenName: 'Dọn dẹp nhà cửa',
        serviceImage: serviceImage,
        serviceName: 'Mama at home',
        time: '8:00 - 10:00 thứ 2 hàng tuần',
        createAt: '2023-10-16T20:47:42',
        startDate: '11/9/2023',
        endDate: '11/12/2023',
        status: Status.CANCEL,
        package: true,
        note: 'Cần nhân viên tuổi 18+, có ngoại hình, chăm chỉ, đảm đang',
    },
    {
        jobId: 4,
        address:
            'Nhà Văn hóa Sinh viên TP.HCM, Lưu Hữu Phước, Đông Hòa, Dĩ An, Bình Dương, Việt Nam',
        serviceChildrenName: 'Dọn dẹp nhà cửa',
        serviceImage: serviceImage,
        serviceName: 'Mama at home',
        time: '8:00 - 10:00 thứ 2 hàng tuần',
        createAt: '2023-10-16T20:47:42',
        startDate: '11/9/2023',
        endDate: '11/12/2023',
        status: Status.CANCEL,
        package: true,
        note: 'Cần nhân viên tuổi 18+, có ngoại hình, chăm chỉ, đảm đang',
    },
    {
        jobId: 5,
        address:
            'Nhà Văn hóa Sinh viên TP.HCM, Lưu Hữu Phước, Đông Hòa, Dĩ An, Bình Dương, Việt Nam',
        serviceChildrenName: 'Dọn dẹp nhà cửa',
        serviceImage: serviceImage,
        serviceName: 'Mama at home',
        time: '8:00 - 10:00 thứ 2 hàng tuần',
        createAt: '2023-10-16T20:47:42',
        startDate: '11/9/2023',
        endDate: '11/12/2023',
        status: Status.CANCEL,
        package: true,
        note: 'Cần nhân viên tuổi 18+, có ngoại hình, chăm chỉ, đảm đang',
    },
    {
        jobId: 6,
        address:
            'Nhà Văn hóa Sinh viên TP.HCM, Lưu Hữu Phước, Đông Hòa, Dĩ An, Bình Dương, Việt Nam',
        serviceChildrenName: 'Dọn dẹp nhà cửa',
        serviceImage: serviceImage,
        serviceName: 'Mama at home',
        time: '8:00 - 10:00 thứ 2 hàng tuần',
        createAt: '2023-10-16T20:47:42',
        startDate: '11/9/2023',
        endDate: '11/12/2023',
        status: Status.CANCEL,
        package: true,
        note: 'Cần nhân viên tuổi 18+, có ngoại hình, chăm chỉ, đảm đang',
    },
    {
        jobId: 7,
        address:
            'Nhà Văn hóa Sinh viên TP.HCM, Lưu Hữu Phước, Đông Hòa, Dĩ An, Bình Dương, Việt Nam',
        serviceChildrenName: 'Dọn dẹp nhà cửa',
        serviceImage: serviceImage,
        serviceName: 'Mama at home',
        time: '8:00 - 10:00 thứ 2 hàng tuần',
        createAt: '2023-10-16T20:47:42',
        startDate: '11/9/2023',
        endDate: '11/12/2023',
        status: Status.CANCEL,
        package: true,
        note: 'Cần nhân viên tuổi 18+, có ngoại hình, chăm chỉ, đảm đang',
    },
    {
        jobId: 8,
        address:
            'Nhà Văn hóa Sinh viên TP.HCM, Lưu Hữu Phước, Đông Hòa, Dĩ An, Bình Dương, Việt Nam',
        serviceChildrenName: 'Dọn dẹp nhà cửa',
        serviceImage: serviceImage,
        serviceName: 'Mama at home',
        time: '8:00 - 10:00 thứ 2 hàng tuần',
        createAt: '2023-10-16T20:47:42',
        startDate: '11/9/2023',
        endDate: '11/12/2023',
        status: Status.CANCEL,
        package: true,
        note: 'Cần nhân viên tuổi 18+, có ngoại hình, chăm chỉ, đảm đang',
    },
    {
        jobId: 9,
        address:
            'Nhà Văn hóa Sinh viên TP.HCM, Lưu Hữu Phước, Đông Hòa, Dĩ An, Bình Dương, Việt Nam',
        serviceChildrenName: 'Dọn dẹp nhà cửa',
        serviceImage: serviceImage,
        serviceName: 'Mama at home',
        time: '8:00 - 10:00 thứ 2 hàng tuần',
        createAt: '2023-10-16T20:47:42',
        startDate: '11/9/2023',
        endDate: '11/12/2023',
        status: Status.CANCEL,
        package: true,
        note: 'Cần nhân viên tuổi 18+, có ngoại hình, chăm chỉ, đảm đang',
    },
    {
        jobId: 10,
        address:
            'Nhà Văn hóa Sinh viên TP.HCM, Lưu Hữu Phước, Đông Hòa, Dĩ An, Bình Dương, Việt Nam',
        serviceChildrenName: 'Dọn dẹp nhà cửa',
        serviceImage: serviceImage,
        serviceName: 'Mama at home',
        time: '8:00 - 10:00 thứ 2 hàng tuần',
        createAt: '2023-10-16T20:47:42',
        startDate: '11/9/2023',
        endDate: '11/12/2023',
        status: Status.CANCEL,
        package: true,
        note: 'Cần nhân viên tuổi 18+, có ngoại hình, chăm chỉ, đảm đang',
    },
];
