const routes = {
    public: {
        home: '/',
        login: '/login',
        register: '/register',
        forgotPassword: '/forgot-password',
        setPassword: '/set-password',
        shop: '/shop',
        serviceDetail: '/shop/:serviceId',
    },
    customer: {
        profile: '/profile',
        cart: '/cart',
        checkout: '/checkout',
        purchased: '/purchased',
        purchasedDetail: '/purchased/:purchasedId',
        viewScheduleDetail: '/purchased/:purchasedId/:taskId',
        orderSuccess: '/confirm',
        schedule: '/schedule',
    },
    staff: {
        home: '/staff',
        profile: '/staff/profile',
        job: '/staff/job',
        newJob: '/staff/job/new',
        waitingConfirmJob: '/staff/job/waiting',
        confirmedJob: '/staff/job/confirmed',
        jobDetail: '/staff/job/:jobId',
        task: '/staff/task',
        doneTask: '/staff/task/done',
        incomingTask: '/staff/task/incoming',
        pendingTask: '/staff/task/pending',
        taskDetail: '/staff/task/:taskId',
    },
    admin: {
        dashboard: '/admin',
        profile: '/admin/profile',
        services: '/admin/services',
        serviceDetail: '/admin/services/:serviceId',
        createSingle: '/admin/create-single-service',
        createPackage: '/admin/create-package-service',
        manageStaff: '/admin/staffs',
        staffDetail: '/admin/staff/:staffId',
        manageCustomer: '/admin/customers',
        customerDetail: '/admin/customers/:customerId',
    },
    api: {
        loginGoogle: '/auth/callback/google/redirect',
    },
};

export default routes;
