// * This file will be deleted if we have data from API

import { Category, SaleStatus } from '@/utils/enums';

// * This is just a dummy data
const services = [
    {
        id: 1,
        titleName: 'Cleaning service',
        oldPrice: 1500,
        salePrice: 100,
        rating: 4.8,
        totalSold: 1300,
        saleStatus: SaleStatus.NOT_AVAILABLE,
        category: Category.SINGLE_SERVICE,
    },
    {
        id: 2,
        titleName: 'Laundry',
        oldPrice: 1500,
        salePrice: 100,
        rating: 4.8,
        totalSold: 1300,
        saleStatus: SaleStatus.AVAILABLE,
        category: Category.SINGLE_SERVICE,
    },
    {
        id: 3,
        titleName: 'Water delivery',
        oldPrice: 1500,
        salePrice: 100,
        rating: 4.8,
        totalSold: 1300,
        saleStatus: SaleStatus.DISCONTINUED,
        category: Category.SINGLE_SERVICE,
    },
    {
        id: 4,
        titleName: 'Water delivery',
        oldPrice: 1500,
        salePrice: 100,
        rating: 4.8,
        totalSold: 1300,
        saleStatus: SaleStatus.NOT_AVAILABLE,
        category: Category.SINGLE_SERVICE,
    },
    {
        id: 5,
        titleName: 'Water delivery',
        oldPrice: 1500,
        salePrice: 100,
        rating: 4.8,
        totalSold: 1300,
        saleStatus: SaleStatus.NOT_AVAILABLE,
        category: Category.SINGLE_SERVICE,
    },
    {
        id: 6,
        titleName: 'Water delivery',
        oldPrice: 1500,
        salePrice: 100,
        rating: 4.8,
        totalSold: 1300,
        saleStatus: SaleStatus.NOT_AVAILABLE,
        category: Category.SINGLE_SERVICE,
    },
    {
        id: 7,
        titleName: 'Water delivery',
        oldPrice: 1500,
        salePrice: 100,
        rating: 4.8,
        totalSold: 1300,
        saleStatus: SaleStatus.NOT_AVAILABLE,
        category: Category.SINGLE_SERVICE,
    },
    {
        id: 8,
        titleName: 'Water delivery',
        oldPrice: 1500,
        salePrice: 100,
        rating: 4.8,
        totalSold: 1300,
        saleStatus: SaleStatus.NOT_AVAILABLE,
        category: Category.SINGLE_SERVICE,
    },
    {
        id: 9,
        titleName: 'Water delivery',
        oldPrice: 1500,
        salePrice: 100,
        rating: 4.8,
        totalSold: 1300,
        saleStatus: SaleStatus.NOT_AVAILABLE,
        category: Category.SINGLE_SERVICE,
    },
    {
        id: 10,
        titleName: 'Water delivery',
        oldPrice: 1500,
        salePrice: 100,
        rating: 4.8,
        totalSold: 1300,
        saleStatus: SaleStatus.NOT_AVAILABLE,
        category: Category.SINGLE_SERVICE,
    },
];

export default services;
