// * This file will be deleted if we have data from API

import { SaleStatus, UnitOfMeasure, GroupType } from '@/utils/enums';

import { ServiceType } from './ServiceItem';

// * This is just a dummy data
const services: ServiceType[] = [
    {
        serviceId: 10,
        titleName: 'Raccoon dog',
        originalPrice: 0,
        finalPrice: 0,
        salePrice: 36,
        unitOfMeasure: UnitOfMeasure.KG,
        description: 'Sbac myl leu wo ach rmsn',
        saleStatus: SaleStatus.AVAILABLE,
        groupType: GroupType.OTHER,
        avgRating: 0,
        numberOfSold: 0,
        mainImg: 'bit.ly/3tsNi4d',
        package: false,
    },
    {
        serviceId: 2,
        titleName: 'Lau nhà',
        originalPrice: 60,
        finalPrice: 24,
        salePrice: 60,
        unitOfMeasure: UnitOfMeasure.KG,
        description: '70-79% bdy brn/40-49% 3d',
        saleStatus: SaleStatus.AVAILABLE,
        groupType: GroupType.HOURLY_SERVICE,
        avgRating: 5,
        numberOfSold: 10266,
        mainImg: 'bit.ly/3tsNi4d',
        package: false,
    },
    {
        serviceId: 63,
        titleName: 'xdxdc',
        originalPrice: 1,
        finalPrice: 1,
        salePrice: 0,
        unitOfMeasure: UnitOfMeasure.HOUR,
        description: 'string',
        saleStatus: SaleStatus.AVAILABLE,
        groupType: GroupType.OTHER,
        avgRating: 0,
        numberOfSold: 0,
        mainImg: 'bit.ly/3tsNi4d',
        package: true,
    },
    {
        serviceId: 84,
        titleName: 'dfasf',
        originalPrice: 2,
        finalPrice: 2,
        salePrice: 0,
        unitOfMeasure: UnitOfMeasure.COMBO,
        description: 'string',
        saleStatus: SaleStatus.AVAILABLE,
        groupType: GroupType.HOURLY_SERVICE,
        avgRating: 0,
        numberOfSold: 0,
        mainImg: 'bit.ly/3tsNi4d',
        package: true,
    },
    {
        serviceId: 71,
        titleName: 'adggdsd',
        originalPrice: 5,
        finalPrice: 5,
        salePrice: 0,
        unitOfMeasure: UnitOfMeasure.COMBO,
        description: 'string',
        saleStatus: SaleStatus.AVAILABLE,
        groupType: GroupType.HOURLY_SERVICE,
        avgRating: 0,
        numberOfSold: 0,
        mainImg: 'bit.ly/3tsNi4d',
        package: true,
    },
    {
        serviceId: 72,
        titleName: 'gsdvs',
        originalPrice: 5,
        finalPrice: 5,
        salePrice: 0,
        unitOfMeasure: UnitOfMeasure.COMBO,
        description: 'string',
        saleStatus: SaleStatus.AVAILABLE,
        groupType: GroupType.HOURLY_SERVICE,
        avgRating: 0,
        numberOfSold: 0,
        mainImg: 'bit.ly/3tsNi4d',
        package: true,
    },
    {
        serviceId: 3,
        titleName: 'DICH VU QUET RAC',
        originalPrice: 60,
        finalPrice: 48,
        salePrice: 20,
        unitOfMeasure: UnitOfMeasure.KG,
        description: 'DICH VU QUET RAC SO 1 VIET NAM',
        saleStatus: SaleStatus.AVAILABLE,
        groupType: GroupType.OTHER,
        avgRating: 2,
        numberOfSold: 45,
        mainImg: 'bit.ly/3tsNi4d',
        package: false,
    },
    {
        serviceId: 73,
        titleName: 'dsgdsadg',
        originalPrice: 56,
        finalPrice: 56,
        salePrice: 0,
        unitOfMeasure: UnitOfMeasure.COMBO,
        description: 'string',
        saleStatus: SaleStatus.AVAILABLE,
        groupType: GroupType.HOURLY_SERVICE,
        avgRating: 0,
        numberOfSold: 0,
        mainImg: 'bit.ly/3tsNi4d',
        package: true,
    },
    {
        serviceId: 74,
        titleName: 'dsgdsasadg',
        originalPrice: 56,
        finalPrice: 56,
        salePrice: 0,
        unitOfMeasure: UnitOfMeasure.COMBO,
        description: 'string',
        saleStatus: SaleStatus.AVAILABLE,
        groupType: GroupType.HOURLY_SERVICE,
        avgRating: 0,
        numberOfSold: 0,
        mainImg: 'bit.ly/3tsNi4d',
        package: true,
    },
    {
        serviceId: 75,
        titleName: 'sgsdgsdgasdg',
        originalPrice: 56,
        finalPrice: 56,
        salePrice: 0,
        unitOfMeasure: UnitOfMeasure.COMBO,
        description: 'string',
        saleStatus: SaleStatus.AVAILABLE,
        groupType: GroupType.HOURLY_SERVICE,
        avgRating: 0,
        numberOfSold: 0,
        mainImg: 'bit.ly/3tsNi4d',
        package: true,
    },
    {
        serviceId: 76,
        titleName: 'haidang',
        originalPrice: 56,
        finalPrice: 56,
        salePrice: 0,
        unitOfMeasure: UnitOfMeasure.COMBO,
        description: 'string',
        saleStatus: SaleStatus.AVAILABLE,
        groupType: GroupType.HOURLY_SERVICE,
        avgRating: 0,
        numberOfSold: 0,
        mainImg: 'bit.ly/3tsNi4d',
        package: true,
    },
    {
        serviceId: 77,
        titleName: 'haidangdsg',
        originalPrice: 56,
        finalPrice: 56,
        salePrice: 0,
        unitOfMeasure: UnitOfMeasure.COMBO,
        description: 'string',
        saleStatus: SaleStatus.AVAILABLE,
        groupType: GroupType.HOURLY_SERVICE,
        avgRating: 0,
        numberOfSold: 0,
        mainImg: 'bit.ly/3tsNi4d',
        package: true,
    },
    {
        serviceId: 86,
        titleName: 'BAN RUA CHEN TOI LAU NHA NEEEEE',
        originalPrice: 420,
        finalPrice: 420,
        salePrice: 0,
        unitOfMeasure: UnitOfMeasure.COMBO,
        description: 'string',
        saleStatus: SaleStatus.AVAILABLE,
        groupType: GroupType.HOURLY_SERVICE,
        avgRating: 0,
        numberOfSold: 0,
        mainImg: 'bit.ly/3tsNi4d',
        package: true,
    },
    {
        serviceId: 13,
        titleName: 'NGOC TRÌNH 578',
        originalPrice: 1000,
        finalPrice: 1000,
        salePrice: 0,
        unitOfMeasure: UnitOfMeasure.KG,
        description: 'string',
        saleStatus: SaleStatus.AVAILABLE,
        groupType: GroupType.HOURLY_SERVICE,
        avgRating: 0,
        numberOfSold: 0,
        mainImg: 'bit.ly/3tsNi4d',
        package: true,
    },
    {
        serviceId: 88,
        titleName: 'agdadsgas',
        originalPrice: 1860,
        finalPrice: 1860,
        salePrice: 0,
        unitOfMeasure: UnitOfMeasure.COMBO,
        description: 'string',
        saleStatus: SaleStatus.AVAILABLE,
        groupType: GroupType.DELIVERY_SERVICE,
        avgRating: 0,
        numberOfSold: 0,
        mainImg: 'bit.ly/3tsNi4d',
        package: true,
    },
    {
        serviceId: 78,
        titleName: 'BAN RUA CHEN TOI LAU NHA',
        originalPrice: 3003,
        finalPrice: 3003,
        salePrice: 0,
        unitOfMeasure: UnitOfMeasure.COMBO,
        description: 'RAT MET MET RAT MET',
        saleStatus: SaleStatus.AVAILABLE,
        groupType: GroupType.HOURLY_SERVICE,
        avgRating: 0,
        numberOfSold: 0,
        mainImg: 'bit.ly/3tsNi4d',
        package: true,
    },
    {
        serviceId: 79,
        titleName: 'RUA CHEN TOI LAU NHA',
        originalPrice: 3003,
        finalPrice: 3003,
        salePrice: 0,
        unitOfMeasure: UnitOfMeasure.COMBO,
        description: 'RAT MET MET RAT MET',
        saleStatus: SaleStatus.AVAILABLE,
        groupType: GroupType.HOURLY_SERVICE,
        avgRating: 0,
        numberOfSold: 0,
        mainImg: 'bit.ly/3tsNi4d',
        package: true,
    },
    {
        serviceId: 80,
        titleName: 'CHEN TOI LAU NHA',
        originalPrice: 3003,
        finalPrice: 3003,
        salePrice: 0,
        unitOfMeasure: UnitOfMeasure.COMBO,
        description: 'RAT MET MET RAT MET',
        saleStatus: SaleStatus.AVAILABLE,
        groupType: GroupType.HOURLY_SERVICE,
        avgRating: 0,
        numberOfSold: 0,
        mainImg: 'bit.ly/3tsNi4d',
        package: true,
    },
    {
        serviceId: 81,
        titleName: 'OI LAU NHA',
        originalPrice: 3003,
        finalPrice: 3003,
        salePrice: 0,
        unitOfMeasure: UnitOfMeasure.COMBO,
        description: 'RAT MET MET RAT MET',
        saleStatus: SaleStatus.AVAILABLE,
        groupType: GroupType.HOURLY_SERVICE,
        avgRating: 0,
        numberOfSold: 0,
        mainImg: 'bit.ly/3tsNi4d',
        package: true,
    },
    {
        serviceId: 82,
        titleName: 'AU NHA',
        originalPrice: 3003,
        finalPrice: 3003,
        salePrice: 0,
        unitOfMeasure: UnitOfMeasure.COMBO,
        description: 'RAT MET MET RAT MET',
        saleStatus: SaleStatus.AVAILABLE,
        groupType: GroupType.HOURLY_SERVICE,
        avgRating: 0,
        numberOfSold: 0,
        mainImg: 'bit.ly/3tsNi4d',
        package: true,
    },
    {
        serviceId: 83,
        titleName: 'NHA NHA',
        originalPrice: 3003,
        finalPrice: 3003,
        salePrice: 0,
        unitOfMeasure: UnitOfMeasure.COMBO,
        description: 'RAT MET MET RAT MET',
        saleStatus: SaleStatus.AVAILABLE,
        groupType: GroupType.HOURLY_SERVICE,
        avgRating: 0,
        numberOfSold: 0,
        mainImg: 'bit.ly/3tsNi4d',
        package: true,
    },
    {
        serviceId: 70,
        titleName: 'TOI RUA CHEN BAN LAU NHA',
        originalPrice: 10000,
        finalPrice: 10000,
        salePrice: 0,
        unitOfMeasure: UnitOfMeasure.HOUR,
        description: 'iot aur nehc nab ual ahn',
        saleStatus: SaleStatus.AVAILABLE,
        groupType: GroupType.HOURLY_SERVICE,
        avgRating: 0,
        numberOfSold: 0,
        mainImg: 'bit.ly/3tsNi4d',
        package: false,
    },
    {
        serviceId: 65,
        titleName: 'stringstria',
        originalPrice: 100000,
        finalPrice: 100000,
        salePrice: 0,
        unitOfMeasure: UnitOfMeasure.COMBO,
        description: 'string',
        saleStatus: SaleStatus.AVAILABLE,
        groupType: GroupType.OTHER,
        avgRating: 0,
        numberOfSold: 0,
        mainImg: 'bit.ly/3tsNi4d',
        package: true,
    },
    {
        serviceId: 66,
        titleName: 'stringstragia',
        originalPrice: 100000,
        finalPrice: 100000,
        salePrice: 0,
        unitOfMeasure: UnitOfMeasure.COMBO,
        description: 'string',
        saleStatus: SaleStatus.AVAILABLE,
        groupType: GroupType.OTHER,
        avgRating: 0,
        numberOfSold: 0,
        mainImg: 'bit.ly/3tsNi4d',
        package: false,
    },
    {
        serviceId: 67,
        titleName: 'stringstrgagagia',
        originalPrice: 100000,
        finalPrice: 100000,
        salePrice: 0,
        unitOfMeasure: UnitOfMeasure.COMBO,
        description: 'string',
        saleStatus: SaleStatus.AVAILABLE,
        groupType: GroupType.OTHER,
        avgRating: 0,
        numberOfSold: 0,
        mainImg: 'bit.ly/3tsNi4d',
        package: false,
    },
    {
        serviceId: 68,
        titleName: 'hàhdfgsfgah',
        originalPrice: 100000,
        finalPrice: 100000,
        salePrice: 0,
        unitOfMeasure: UnitOfMeasure.COMBO,
        description: 'string',
        saleStatus: SaleStatus.AVAILABLE,
        groupType: GroupType.OTHER,
        avgRating: 0,
        numberOfSold: 0,
        mainImg: 'bit.ly/3tsNi4d',
        package: true,
    },
    {
        serviceId: 69,
        titleName: 'hàhdfgsfgaha',
        originalPrice: 100000,
        finalPrice: 100000,
        salePrice: 0,
        unitOfMeasure: UnitOfMeasure.COMBO,
        description: 'string',
        saleStatus: SaleStatus.AVAILABLE,
        groupType: GroupType.OTHER,
        avgRating: 0,
        numberOfSold: 0,
        mainImg: 'bit.ly/3tsNi4d',
        package: true,
    },
];

export default services;
